bamboo-data:
    image: busybox
    tty: true
    volumes:
        - /home/bamboo

bamboo-server:
    image: matisq/bamboo-server:latest
    ports:
        - ${http_port}:8085
        - ${agent_port}:54663
    links:
        - postgres:postgres
    environment:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        BAMBOO_VERSION: ${bamboo_version}
        BAMBOO_BAMBOO_SERVER_ID: bamboo-server
    labels:
        io.rancher.sidekicks: bamboo-data
    volumes_from:
        - bamboo-data

postgres-data:
    image: busybox
    tty: true
    volumes:
        - /var/lib/postgresql/data/pgdata

postgres:
    image: postgres:latest
    ports:
        - ${postgress_port}:5432
    environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_DB: ${postgres_db}
        POSTGRES_USER: ${postgres_user}
        POSTGRES_PASSWORD: ${postgres_password}
    tty: true
    stdin_open: true
    labels:
        io.rancher.sidekicks: postgres-data
    volumes_from:
        - postgres-data

bamboo-agent:
    image: matisq/bamboo-agent:latest
    links:
        - bamboo-server:bamboo-server
    environment:
        AGENT_VERSION: ${bamboo_version}
        BAMBOO_SERVER: bamboo-server
        BAMBOO_SERVER_PORT: 8085
